### ISSUE TITLE
netcdf-by-coordinates examples fail when NaNs in data

### ISSUE THREAD

**Issue by danwild** [Unidata/python-workshop#117]
Firstly - thanks for the examples, they are very helpful!

Just wanted to note that the supplied code examples fail when NaN's are in the dataset (which in my experience tends to be pretty frequent).

I'm currently using the `Naive_fast` approach, aka numpy - which fortunately seems to have a simple way to handle the NaN problem, by changing this line:

```
# argmin trips over NaN's
minindex_flattened = dist_sq.argmin()        
```              

To this:

```
# nanargmin handles NaN's
minindex_flattened = np.nanargmin(dist_sq)
```
        
Sorry; I'd prefer to submit a PR with fixes for other approaches too but haven't the time right now :(

**Comment by jrleeman** [comment]
This material has been removed.
