### ISSUE TITLE
Improve Primer Materials

### ISSUE THREAD

**Issue by jrleeman** [Unidata/python-workshop#203]
- [ ] Remove unneeded `rad2deg` call when calculating the wind direction.
- [ ] Show how to use `.magnitude` to strip units.

**Comment by jrleeman** [comment]
Shouldn't we kill the primer materials now that there is introduction to MetPy, Numpy, and Matplotlib notebooks?

**Comment by dopplershift** [comment]
Primer and exercises notebook can go. Should split and move NumPy/Matplotlib basics to their respective units.
