### ISSUE TITLE
Improvements for NCSS model

### ISSUE THREAD

**Issue by dopplershift** [Unidata/python-workshop#216]
- Define variable once at top and use for both request and extraction from netCDF4 `Dataset`

**Comment by jrleeman** [comment]
Relevant @dopplershift ?

**Comment by dopplershift** [comment]
Still relevant. Probably easy to pick off though.

**Comment by zbruick** [comment]
This notebook was updated to use xarray since this issue was filed. I'm not sure if it makes sense to do this now as it doesn't necessarily make the code any cleaner IMO.

**Comment by dopplershift** [comment]
Let's drop it then.
