### ISSUE TITLE
Transition to Jupyter Lab

### ISSUE THREAD

**Issue by jrleeman** [Unidata/python-workshop#274]
Now that Jupyter Lab is officially ready for use - should we be teaching with it instead of just notebooks? Integrated terminal, etc could make platform issues less difficult for students. Will just need it added to the environment.

**Comment by dopplershift** [comment]
The question is: does integrated terminal actually work on windows?

**Comment by jrleeman** [comment]
I'll have to fire up the surface and play with it.

**Comment by jrleeman** [comment]
We're changing the solutions back to load magics #381 - so this is solid now and we're going to teach with lab.
