### ISSUE TITLE
Skew-T notebook most unstable CAPE

### ISSUE THREAD

**Issue by dopplershift** [Unidata/python-workshop#354]
Need to look into why the CIN is different between surface-based CAPE/CIN and most-unstable CAPE/CIN, since the CAPE values are identical.

**Comment by zbruick** [comment]
Skew-T notebooks were refactored in #377, and most-unstable CAPE is no longer used in the Skew-T notebook.

**Comment by dopplershift** [comment]
Can you grab the notebook from that era and see if this is still an issue with current MetPy? I'm concerned there's a MetPy bug lurking. This is not the ideal place to hold onto such things, but I'm pretty sure I opened this issue with every intention of looking at it right after the workshop.

**Comment by zbruick** [comment]
Will do!

**Comment by zbruick** [comment]
This is clearly a bug in MetPy, just looking at the tests we already have. Going to open in issue over there.

**Comment by dopplershift** [comment]
😭
