### ISSUE TITLE
Isentropic Analysis

### ISSUE THREAD

**Issue by dopplershift** [Unidata/python-workshop#372]
- [x] Use `.metpy` accessor to get coordinates
- [x] Replace manual call to `scipy.ndimage.gaussian_filter` with `smooth_gaussian`

**Comment by jrleeman** [comment]
So 
```
dat = ds.metpy.parse_cf('Temperature_isobaric')
```
ends up giving us
```
/Users/johnleeman/miniconda3/envs/unidata/lib/python3.7/site-packages/metpy/xarray.py:169: UserWarning: Could not find variable corresponding to the value of grid_mapping: LatLon_Projection
  'grid_mapping: {}'.format(proj_name))
```

So do we want to handle that? Make things a bit more flexible?

**Comment by lesserwhirls** [comment]
No idea why it's not returned in 4.6. We return it in 5.0, so that's a bonus. I could try to get this fixed in 4, but it's out there already. Maybe if the variable isn't there, we could warn the user and use a default datum?

**Comment by lesserwhirls** [comment]
Actually, we get the lat / lon variables themselves (even if I say `addLatLon=false`), and the `coordinates` attribute points to them, so do we need to do the projection math here?

**Comment by dopplershift** [comment]
We don't need to do projection math, but the files aren't CF-compliant since `grid_mapping` points to a non-existent variable. So long as the model output doesn't need to describe a particular globe, the `grid_mapping` isn't even required.

To be clear, MetPy is already falling back to creating a `latitude_longitude` CRS because it finds latitude and longitude coordinates. But it warns because the metadata tells it to look for a variable and it finds none.

**Comment by dopplershift** [comment]
Regardless of if @lesserwhirls does anything to thredds, since we're not erroring out, I think the right thing to do in MetPy is to make it a logged warning, like we do for NEXRAD file errors, rather than `warnings.warn` which we use to imply the user is doing something that could/should be adjusted.

See Unidata/MetPy#974.

**Comment by lesserwhirls** [comment]
The `UserWarning` reported in https://github.com/Unidata/python-workshop/issues/372#issuecomment-444279129 will no longer be triggered by the TDS as of 4.6.12 (Unidata/thredds#1197).
