### ISSUE TITLE
Xarray improvements 

### ISSUE THREAD

**Issue by dopplershift** [Unidata/python-workshop#416]
- `loc` example dim ordering wrong—should be lat, lon
- Missing units on one y range value

**Comment by zbruick** [comment]
Can you clarify what you mean by the second bullet point? I found the first one already.

**Comment by dopplershift** [comment]
I don't know what you're talking about, my directions were perfectly clear 😆 I managed to find it again:

![image](https://user-images.githubusercontent.com/221526/61724287-e5f85680-ad2a-11e9-9f40-fbc810b7db96.png)

Note the lack of "km" on the first value in the y range.

**Comment by zbruick** [comment]
Ah got it now. Nothing I like more than deciphering cryptic comments on GitHub.
