### ISSUE TITLE
Notes from Albany

### ISSUE THREAD

**Issue by dopplershift** [Unidata/python-workshop#418]
General notes from the last workshop, with a few possible actions:

* Drop some/all of Jupyter — can pick up from videos, many people experienced
* Drop Conda? In favor of explanation of overall ecosystem, motivating why we cover each. General workflow?
* Current normal Day 1 is overloaded
* Would be great to come up with a set of “put it all together exercises”
* Matplotlib allocation is off from what’s in the notebook

**Comment by zbruick** [comment]
The only remaining item that hasn't been addressed is the "put it all together" exercises. I don't know if we need that for Valpo, or if we should just open that as a separate issue for longer-term development?

**Comment by dopplershift** [comment]
If a good general exercise comes to mind, we can look at including it for Valpo. Otherwise, let's just pull it out into its own issue.

If @kgoebber has any ideas, that would be welcome as well.

**Comment by kgoebber** [comment]
I don't have any big ideas right off the top of my head, but to some extent the QG Analysis notebook brings together a number of different aspects: data acquisition, data computation, and data plotting on a map. Another example was the case study piece that we did for the AMS workshop in 2018 (I think) as that brought together skew-T, Satellite, and model output.

I agree that this should be opened as a separate issue to iterate on to develop some good "pull it all together" exercises. Thinking problem-based might help with identifying interesting examples.

**Comment by zbruick** [comment]
Thanks for the input! I think a case study would be the obvious solution here, but something problem-based that maybe could be tweaked for the audience would be useful overall. I've opened #437 to handle this topic and we can iterate on it over there.

I'm closing this issue, since we'll handle the remaining issue in #437, as discussed.
