### ISSUE TITLE
Valpo Workshop To-Do

### ISSUE THREAD

**Issue by zbruick** [Unidata/python-workshop#435]
- [x] Decide teaching order
- [x] Create Python Ecosystem presentation (if kept in #427)

**Comment by zbruick** [comment]
Pinging @dopplershift on the Python Ecosystem issue here. Thoughts?

I assume this would quickly touch on Jupyter, Anaconda, and the SciPy ecosystem? Anything else? Anything interactive here?

**Comment by dopplershift** [comment]
I was thinking we could introduce a lot of packages, maybe with a minute or two on each. The goal being that we can give people the lay of the land before we go running into the details and working with things. Things that come to mind:

* Getting Python Anaconda/Miniconda
* Jupyter
* NumPy, Pandas, Xarray
* SciPy
* Matplotlib, CartoPy
* scikit-learn, scikit-image
* Dask
* pint
* netcdf4-Python, MetPy, Siphon, pyart

The goal being that people might understand some idea of what tools we're reaching for and why. Does that help?

**Comment by dopplershift** [comment]
Might also want to start with an explanation that Python is a language + an ecosystem of packages that work together like legos.

**Comment by zbruick** [comment]
Ok sounds good. That all makes sense to me. Just wanted to get your input first before working on putting anything together. I'll add that to the to-do list for tomorrow.

**Comment by dopplershift** [comment]
We've put together the order, and merged in the ecosystem notebook, so I think we're good here.
